name: Build

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: List theories
        run: ls -l .
      - name: Run theories  
        uses: docker://makarius/isabelle
        args: build -d /github/workspace Finite