name: Build
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v1
        with:
          path: /tmp/docker-cache
          key: docker-cache-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            docker-cache-

      - name: Build Isabelle
        run: |
            docker buildx build \
                --cache-from "type=local,src=/tmp/docker-cache" \
                --cache-to "type=local,dest=/tmp/docker-cache,mode=max" \
                --output "type=docker" \
                --tag isabelle:latest .

      - name: Run theories
        run: docker run isabelle build -d . Finite