name: Build

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    container: makarius/isabelle
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run theories
        run: isabelle build -d . Finite