name: Build
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: List 1
        run: ls -l .
      
      - name: List 2
        run: ls -l $GITHUB_WORKSPACE

      - name: workspace
        run: echo "$GITHUB_WORKSPACE"

      - name: Run theories
        run: docker run makarius/isabelle build -d /github/workspace Finite