name: Build

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    container:
      image: makarius/isabelle
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: List theories
        run: ls -l .
      - name: Run theories
        run: Isabelle/bin/isabelle build -d . Finite